### ISSUE TITLE
sqlboiler v5 tracking issue

### ISSUE THREAD

**Issue by aarondl** [volatiletech/sqlboiler#965]
The following are loose goals that will be tackled in sqlboiler v5

Goals
- [ ] Fearless ability to load relationships (should use joins, each relationship load should be distinct)
- [ ] Opening up the query mod system for extension
- [ ] Removal of the .R struct (maybe)
- [ ] Ability to use left/right joins more easily
- [ ] Updated null package

**Comment by aarondl** [comment]
Why didn't I use a milestone -_-
